### ISSUE TITLE
Potential dependency conflicts between basecampy3r and chardet

### ISSUE THREAD

**Issue by NeolithEra** [phistrom/basecampy3#12]
Hi, as shown in the following full dependency graph of  **_basecampy3r_**, **_basecampy3r_** requires **_chardet  *_** ， while the installed version of **_requests_**(2.22.0) requires _**chardet <3.1.0,>=3.0.2**_.

According to Pip's _“first found wins”_ installation strategy, _**chardet 3.0.4**_ is the actually installed version.  

Although the first found package version _**chardet 3.0.4**_ just satisfies the later dependency constraint （_**chardet <3.1.0,>=3.0.2**_), it will lead to a build failure once developers release a newer version of chardet.

### Dependency tree--------
```
basecampy3r - 0.2.2
| +- beautifulsoup4(install version:4.8.1 version range:*)
| | +- soupsieve(install version:1.9.5 version range:>=1.2)
| +- certifi(install version:2019.9.11 version range:*)
| +- chardet(install version:3.0.4 version range:*)
| +- idna(install version:2.8 version range:*)
| +- python-dateutil(install version:2.8.1 version range:*)
| +- requests(install version:2.22.0 version range:*)
| | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.6 version range:<1.26,>=1.21.1)
| +- six(install version:1.13.0 version range:*)
| +- urllib3(install version:1.25.6 version range:*)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependencies to be **_chardet  <3.1.0_**.
2.	Ask your upstream project **_request_** to losse the version range of **_chardet_** to be **_>=3.0.2_**.

Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by phistrom** [comment]
Thanks! Please see my response to #10 . This should be resolved now.
