### ISSUE TITLE
class Basecamp3 constructor ingores argument conf: basecampy3.config.BasecampConfig

### ISSUE THREAD

**Issue by timecamp-analityk** [phistrom/basecampy3#13]
at constructor, if a config is passed,
if there is data to create a new config, a new config is created and argument is ignored
if there is no data to create a new config, but a config was passed in argument, error is raised

```        if access_token or can_refresh_access_tokens or can_request_our_own_refresh_tokens:
            conf = BasecampConfig(client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri,
                                  user_email=user_email, user_pass=user_pass, access_token=access_token,
                                  refresh_token=refresh_token, access_expires=access_expires)
        elif conf is None:
            conf = BasecampConfig.load_from_default_paths()
        else:
            raise ValueError("Need a valid BasecampConfig object, a refresh token, an access token, or enough "
                             "information to get our own refresh tokens (client_id, client_secret, redirect_uri, "
                             "username, and password)")```

**Comment by phistrom** [comment]
Thanks for opening this issue! This was intended. If you specified parameters directly, you should not also specify a config object. This is made more explicit as of version 0.3.0 by raising a ValueError if any field is specified in addition to the conf field.

Let me know if I misunderstood your issue and/or if it is resolved now.

**Comment by timecamp-analityk** [comment]
commit f27f1e66b53f4a3695df3458fdacf3785fa3d5ce made this not relevant.
