### ISSUE TITLE
boolean capitalization

### ISSUE THREAD

**Issue by rbgorbet** [phistrom/basecampy3#17]
Thanks for this tool!

I'm not sure if this is on the Basecamp API side or the library, but booleans are returned capitalized, which isn't valid JSON.  Also an empty field or one which doesn't exist should probably return an empty string (or null) rather than None which isn't valid JSON either.  See https://www.json.org/json-en.html

as received:
![image](https://user-images.githubusercontent.com/6044957/101224239-13158280-365c-11eb-954c-ca96789865e9.png)

fixed:
![image](https://user-images.githubusercontent.com/6044957/101224337-4b1cc580-365c-11eb-9cf7-8a9c12044a61.png)

**Comment by rbgorbet** [comment]
Actually...it's `pprint(resp.json())` from the example in the readme that is the culprit.  Using `json.dump(resp.json(),indent=3)` solves the "problem".

I realize now my goal is a special case:  I'm creating files to transfer to someone else, so need them to be JSON-compatible. `pprint` works fine if all you want to do is visualize, but it produces output that isn't valid JSON.  Not sure whether you want to add this clarification to the sample code, but it would have saved me a lot of confusion.  :-)

**Comment by phistrom** [comment]
Sorry about that. I know it is very late, but the example has been changed in 2cdf41d to avoid such an insidious problem afflicting anyone else.
