### ISSUE TITLE
Thank you for building basecampy3!

### ISSUE THREAD

**Issue by nategadzhi** [phistrom/basecampy3#21]
Hey @licht1stein and @phistrom!

I needed to bulk-export our data from Basecamp and upload it to Jira, found Basecampy, and built a small tool with it (https://github.com/nategadzhi/baseport). Just wanted to say thank you for all your time and effort that went into building it, it helped me a lot and saved us a ton of time. 👏

**Comment by licht1stein** [comment]
Hi, I did very little on this project. It was all @phistrom

**Comment by phistrom** [comment]
Thank you so much for the kind words! It means a lot!
