### ISSUE TITLE
Add comments support?

### ISSUE THREAD

**Issue by nategadzhi** [phistrom/basecampy3#22]
Hi again, @phistrom! 

I'd love to also be able to grab the comments from the todo items, and it seems that comments are just attached to recordings on BC api, and I can put together a recording endpoint class for them. 

I'd be happy to work on it and contribute to basecampy3 if that's fine and if you'll have 15 minutes to review the PR. Or maybe I'm missing something and there's a way to fetch comments with what's already in the library?

**Comment by phistrom** [comment]
I'm _happy_ to receive any contributions you wish to make. I'm afraid I have not worked on this project in some time so I may be a tad rusty, but it looks like you're right, comments are not supported (at least, not in an intuitive way).

I'm going to take some time tonight to re-familiarize myself with the project and maybe do a little housekeeping.

**Comment by nategadzhi** [comment]
Also happy to help with other low hanging fruit like GitHub action linters and poetry migration, but not sure how much time I’ll have — expect a couple PRs on Sunday. 

Nate
(650) 933-7237

**Comment by phistrom** [comment]
Comment support has been added as of 90fca54 (v0.6.0).
