### ISSUE TITLE
Setup.py version conflict

### ISSUE THREAD

**Issue by Randomneo** [phistrom/basecampy3#7]
In my project used different version of same depended packages.
And when im installing this package i get this error
```
pkg_resources.ContextualVersionConflict: (beautifulsoup4 4.6.3 (/opt/rp/env/lib/python2.7/site-packages), Requirement.parse('beautifulsoup4==4.6.0'), set(['basecampy3']))
```
May be its better to remove versions and leave them only in requirements.txt
```
    install_requires=[
        "beautifulsoup4",
        "certifi",
        "chardet",
        "idna",
        "python-dateutil",
        "requests",
        "six",
        "urllib3",
    ],
```

**Comment by phistrom** [comment]
Thanks for opening this issue! As of BasecamPY3 v0.3.0, versions have been removed from `setup.py`. Version ranges have been specified in `requirements.txt`.
